#!/usr/bin/env bash
#install nginx
apt-get update -y
apt-get install -y nginx
mkdir -p /var/www/html/
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
service nginx start
service nginx restart
