#!/usr/bin/env bash
#install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
sudo sed -i  s/"\# pass".*/"location \/redirect_me \{\n\t\treturn 301 https\:\/\/www.youtube.com\/watch?v=nQAdYNB8nXU\;\n\t\}"/ /etc/nginx/sites-enabled/default
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i s/"\# include snip".*/"error_page 404 \/404.html;\n\tlocation  \/404.html \{\n\t\tinternal\;\n\t\}"/ /etc/nginx/sites-enabled/default
sudo service nginx restart
