#!/usr/bin/env bash
#install nginx
apt-get update -y
apt-get install -y nginx
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
#sed -z 's/{\n/{\n\trewrite ^\/redirect_me http:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4\n permanent/' -i /etc/nginx/sites-available/default
sed -i  s/"\# pass".*/"location \/redirect_me \{\n\t\treturn 301 https\:\/\/www.youtube.com\/watch?v=nQAdYNB8nXU\;\n\t\}"/ /etc/nginx/sites-enabled/default
sed -i s/"\tlocation\ \/\ ".*/"\tlocation \/ \{\n\t\tadd_header X-Served-By \"$HOSTNAME\"\;"/ /etc/nginx/sites-enabled/default
service nginx restart
