#!/usr/bin/env bash
#Install Load balancer

apt -y update
apt install -y haproxy
service haproxy start
echo "ENABLED=1" > /etc/default/haproxy
echo "global
	log 127.0.0.1 local0 notice
	maxconn 150
	user haproxy
	group haproxy
defaults
	log     global
	mode    http
	option  httplog
	retries 3
	option redispatch
	timeout connect  5000
	timeout client  10000
	timeout server  10000
listen myserv
	bind 0.0.0.0:80
	balance roundrobin
	server 2490-web-01 35.231.210.244:80 check
	server 2490-web-02 34.73.245.217:80 check" > /etc/haproxy/haproxy.cfg
service haproxy start
