#!/usr/bin/env bash
# change local host and facebook to google
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost\n8.8.8.8 facebook/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
