#!/usr/bin/env bash
# set default nginx user
service nginx restart
echo 'user nginx;' >> /etc/nginx/nginx.conf
chown nginx /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
service nginx restart
