#!/usr/bin/env bash
# set default nginx user
sudo pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod u+r /etc/nginx/nginx.conf
chown nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
